/**
 * Applies checked-in SQL migrations (drizzle/*.sql, generated by
 * `npm run db:generate`, never hand-edited) to whatever database
 * DATABASE_URL points at. Deliberately a plain script, not a CI workflow —
 * a migration CI workflow is out of scope for KAN-10 pending Irina's review
 * of that record; run this by hand (or from Vitest's DB test setup) for now.
 */
import { config } from 'dotenv';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';

// quiet: true — see the comment in drizzle.config.ts on dotenv@17's
// self-promotional console "tips".
config({ path: '.env.local', quiet: true });

async function main() {
  if (!process.env.DATABASE_URL) {
    throw new Error('DATABASE_URL is not set — see website/.env.example');
  }
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzle(pool);
  await migrate(db, { migrationsFolder: './drizzle' });
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
